services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: mlflow_postgres
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
    volumes:
      - postgres_data:/bitnami/postgresql
    ports:
      - "5433:5432"

  minio:
    image: bitnami/minio:latest
    container_name: mlflow_minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}
    command: server /bitnami/minio/data --console-address ":9001"
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web console
    volumes:
      - minio_data:/bitnami/minio/data

  minio-init:
    image: bitnami/minio-client:latest
    depends_on:
      - minio
    entrypoint: ["/bin/sh", "/init.sh"]
    volumes:
      - ./scripts/init.sh:/init.sh

  mlflow:
    image: bitnami/mlflow:latest
    container_name: mlflow_server
    depends_on:
      - postgres
      - minio
    environment:
      - MLFLOW_BACKEND_STORE_URI=${MLFLOW_BACKEND_STORE_URI}
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=${MLFLOW_DEFAULT_ARTIFACT_ROOT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
    ports:
      - "5000:5000"
    entrypoint: ["mlflow"]
    command:
      - server
      - --backend-store-uri=${MLFLOW_BACKEND_STORE_URI}
      - --default-artifact-root=${MLFLOW_DEFAULT_ARTIFACT_ROOT}
      - --host=0.0.0.0
      - --port=5000
      - --serve-artifacts

volumes:
  postgres_data:
  minio_data:
