site_name: NYC House Price Prediction
site_url: https://presmanes3.github.io/NY-House-PricingPrediction/

theme:
  name: material

nav:
  - Home: index.md
  - Problem Analysis: eda.md
  - Business Requirements: business.md
  - Playground: playground.md 
  
markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences