site_name: NYC House Price Prediction
theme:
  name: material

nav:
  - Home: index.md
  - Problem Analysis: eda.md

markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences